services:
  backend:
    build: ./backend
    container_name: napicsepp-backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_USER: napicsepp
      DB_PASSWORD: jelszo
      DATABASE: napicsepp
      JWT_SECRET: secret
    depends_on:
      - db
    networks:
      - napicsepp-net

  frontend:
    build: ./frontend
    container_name: napicsepp-frontend
    ports:
      - "5173:5173"
    networks:
      - napicsepp-net

  db:
    image: mysql:8.0
    container_name: napicsepp-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: napicsepp
      MYSQL_USER: napicsepp
      MYSQL_PASSWORD: jelszo
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/mysql
    networks:
      - napicsepp-net

networks:
  napicsepp-net:
    driver: bridge

volumes:
  db-data:
